

def get_problem_list():
    problem_list = [
                    {'W_max': 1, 'W': [1], 'p': 1, 'routing': 'star'},
                    {'W_max': 1, 'W': [1], 'p': 2, 'routing': 'star'},
                    {'W_max': 1, 'W': [1], 'p': 3, 'routing': 'star'},
                    {'W_max': 1, 'W': [1], 'p': 4, 'routing': 'star'},
                    {'W_max': 1, 'W': [1], 'p': 5, 'routing': 'star'},
                    {'W_max': 1, 'W': [1], 'p': 6, 'routing': 'star'},
                    {'W_max': 1, 'W': [1], 'p': 7, 'routing': 'star'},
                    
                    {'W_max': 1, 'W': [1], 'p': 1, 'routing': 'line'},
                    {'W_max': 1, 'W': [1], 'p': 2, 'routing': 'line'},
                    {'W_max': 1, 'W': [1], 'p': 3, 'routing': 'line'},
                    {'W_max': 1, 'W': [1], 'p': 4, 'routing': 'line'},
                    {'W_max': 1, 'W': [1], 'p': 5, 'routing': 'line'},
                    {'W_max': 1, 'W': [1], 'p': 6, 'routing': 'line'},
                    {'W_max': 1, 'W': [1], 'p': 7, 'routing': 'line'},

                    {'W_max': 1, 'W': [1], 'p': 1, 'routing': 'transpile'},
                    {'W_max': 1, 'W': [1], 'p': 2, 'routing': 'transpile'},
                    {'W_max': 1, 'W': [1], 'p': 3, 'routing': 'transpile'},
                    {'W_max': 1, 'W': [1], 'p': 4, 'routing': 'transpile'},
                    {'W_max': 1, 'W': [1], 'p': 5, 'routing': 'transpile'},
                    {'W_max': 1, 'W': [1], 'p': 6, 'routing': 'transpile'},
                    {'W_max': 1, 'W': [1], 'p': 7, 'routing': 'transpile'},

                    {'W_max': 1, 'W': [1], 'p': 1, 'routing': 'linegrid'},
                    {'W_max': 1, 'W': [1], 'p': 2, 'routing': 'linegrid'},
                    {'W_max': 1, 'W': [1], 'p': 3, 'routing': 'linegrid'},
                    {'W_max': 1, 'W': [1], 'p': 4, 'routing': 'linegrid'},
                    {'W_max': 1, 'W': [1], 'p': 5, 'routing': 'linegrid'},
                    {'W_max': 1, 'W': [1], 'p': 6, 'routing': 'linegrid'},
                    {'W_max': 1, 'W': [1], 'p': 7, 'routing': 'linegrid'},

                    {'W_max': 1, 'W': [1], 'p': 1, 'routing': 'network'},
                    {'W_max': 1, 'W': [1], 'p': 2, 'routing': 'network'},
                    {'W_max': 1, 'W': [1], 'p': 3, 'routing': 'network'},
                    {'W_max': 1, 'W': [1], 'p': 4, 'routing': 'network'},
                    {'W_max': 1, 'W': [1], 'p': 5, 'routing': 'network'},
                    {'W_max': 1, 'W': [1], 'p': 6, 'routing': 'network'},
                    {'W_max': 1, 'W': [1], 'p': 7, 'routing': 'network'},


                    {'W_max': 2, 'W': [1, 1], 'p': 1, 'routing': 'star'},
                    {'W_max': 2, 'W': [1, 1], 'p': 2, 'routing': 'star'},
                    {'W_max': 2, 'W': [1, 1], 'p': 3, 'routing': 'star'},
                    {'W_max': 2, 'W': [1, 1], 'p': 4, 'routing': 'star'},
                    {'W_max': 2, 'W': [1, 1], 'p': 5, 'routing': 'star'},
                    {'W_max': 2, 'W': [1, 1], 'p': 6, 'routing': 'star'},
                    {'W_max': 2, 'W': [1, 1], 'p': 7, 'routing': 'star'},
                    
                    {'W_max': 2, 'W': [1, 1], 'p': 1, 'routing': 'line'},
                    {'W_max': 2, 'W': [1, 1], 'p': 2, 'routing': 'line'},
                    {'W_max': 2, 'W': [1, 1], 'p': 3, 'routing': 'line'},
                    {'W_max': 2, 'W': [1, 1], 'p': 4, 'routing': 'line'},
                    {'W_max': 2, 'W': [1, 1], 'p': 5, 'routing': 'line'},
                    {'W_max': 2, 'W': [1, 1], 'p': 6, 'routing': 'line'},
                    {'W_max': 2, 'W': [1, 1], 'p': 7, 'routing': 'line'},

                    {'W_max': 2, 'W': [1, 1], 'p': 1, 'routing': 'transpile'},
                    {'W_max': 2, 'W': [1, 1], 'p': 2, 'routing': 'transpile'},
                    {'W_max': 2, 'W': [1, 1], 'p': 3, 'routing': 'transpile'},
                    {'W_max': 2, 'W': [1, 1], 'p': 4, 'routing': 'transpile'},
                    {'W_max': 2, 'W': [1, 1], 'p': 5, 'routing': 'transpile'},
                    {'W_max': 2, 'W': [1, 1], 'p': 6, 'routing': 'transpile'},
                    {'W_max': 2, 'W': [1, 1], 'p': 7, 'routing': 'transpile'},

                    {'W_max': 2, 'W': [1, 1], 'p': 1, 'routing': 'linegrid'},
                    {'W_max': 2, 'W': [1, 1], 'p': 2, 'routing': 'linegrid'},
                    {'W_max': 2, 'W': [1, 1], 'p': 3, 'routing': 'linegrid'},
                    {'W_max': 2, 'W': [1, 1], 'p': 4, 'routing': 'linegrid'},
                    {'W_max': 2, 'W': [1, 1], 'p': 5, 'routing': 'linegrid'},
                    {'W_max': 2, 'W': [1, 1], 'p': 6, 'routing': 'linegrid'},
                    {'W_max': 2, 'W': [1, 1], 'p': 7, 'routing': 'linegrid'},

                    {'W_max': 2, 'W': [1, 1], 'p': 1, 'routing': 'network'},
                    {'W_max': 2, 'W': [1, 1], 'p': 2, 'routing': 'network'},
                    {'W_max': 2, 'W': [1, 1], 'p': 3, 'routing': 'network'},
                    {'W_max': 2, 'W': [1, 1], 'p': 4, 'routing': 'network'},
                    {'W_max': 2, 'W': [1, 1], 'p': 5, 'routing': 'network'},
                    {'W_max': 2, 'W': [1, 1], 'p': 6, 'routing': 'network'},
                    {'W_max': 2, 'W': [1, 1], 'p': 7, 'routing': 'network'},


                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 1, 'routing': 'star'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 2, 'routing': 'star'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 3, 'routing': 'star'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 4, 'routing': 'star'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 5, 'routing': 'star'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 6, 'routing': 'star'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 7, 'routing': 'star'},
                    #
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 1, 'routing': 'line'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 2, 'routing': 'line'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 3, 'routing': 'line'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 4, 'routing': 'line'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 5, 'routing': 'line'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 6, 'routing': 'line'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 7, 'routing': 'line'},

                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 1, 'routing': 'transpile'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 2, 'routing': 'transpile'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 3, 'routing': 'transpile'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 4, 'routing': 'transpile'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 5, 'routing': 'transpile'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 6, 'routing': 'transpile'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 7, 'routing': 'transpile'},

                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 1, 'routing': 'linegrid'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 2, 'routing': 'linegrid'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 3, 'routing': 'linegrid'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 4, 'routing': 'linegrid'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 5, 'routing': 'linegrid'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 6, 'routing': 'linegrid'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 7, 'routing': 'linegrid'},

                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 1, 'routing': 'network'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 2, 'routing': 'network'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 3, 'routing': 'network'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 4, 'routing': 'network'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 5, 'routing': 'network'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 6, 'routing': 'network'},
                    #{'W_max': 1, 'W': [1, 1, 1], 'p': 7, 'routing': 'network'},

                    ]

    return problem_list
